### ISSUE TITLE
Rename labels to be more consistent

### ISSUE THREAD

**Issue by marcbachmann** [infinityworks/prometheus-rancher-exporter#31]
Currently the `rancher_stack_health_status` and `rancher_service_*` metrics both have a `name`.
In some cases it's a stack name and sometimes a service name.

It would be nice to have a more consistent naming of labels. I advise to rename the labels to `stack_name` and `service_name`.
What do you think about that?

Here's how my metric relabel config looks like.

```
    metric_relabel_configs:
      - action: 'replace'
        source_labels: ['__name__', 'name']
        regex: 'rancher_stack_health_status;(.+)'
        target_label: 'stack_name'

      - action: 'replace'
        source_labels: ['__name__', 'name']
        regex: '(rancher_service_health_status|rancher_service_scale|rancher_service_state);(.+)'
        replacement: '$2'
        target_label: 'service_name'

      - action: 'replace'
        source_labels: ['__name__', 'exported_stack_name']
        regex: '(rancher_service_health_status|rancher_service_scale|rancher_service_state);(.+)'
        replacement: '$2'
        target_label: 'stack_name'

      - action: 'replace'
        source_labels: ['__name__']
        regex: 'rancher_service_[a-z_]*'
        replacement: ''
        target_label: 'exported_stack_name'

      - action: 'replace'
        source_labels: ['__name__']
        regex: '(rancher_stack_health_status|rancher_service_health_status|rancher_service_scale|rancher_service_state)'
        replacement: ''
        target_label: 'name'
```
